name: updateRss

on:
  schedule:
    - cron: '5 * * * *'

jobs:
  build:
    # comment
    name: "add hackNews"
    # comment
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: checkout actions
