name: updateRss

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    # comment
    name: "add hackNews"
    # comment
    runs-on: ubuntu-latest

    steps:
      - name: checkout actions
        uses: actions/checkout@v1
        
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: install packages
        run: "pip install --upgrade pip && pip install -r ./requirements.txt"
  
      - name: Update rss
        run: |
          cd ./src
          python -u ./update_rss.py

      - name: Commit report
        env:
            GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          git config --global user.name 'wa008'
          git config --global user.email 'huzhipeng1024@outlook.com'
          git remote set-url origin https://wa008:${{ secrets.ACCESS_TOKEN }}@github.com/wa008/zhblog.git
          git checkout -b main
          git branch
          git add ./index.md
          git add ./src/valid_rss.txt
          git commit -m "github workflows auto update rss"
          git push origin main

