name: updateRss

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    # comment
    name: "add hackNews"
    # comment
    runs-on: ubuntu-latest

    steps:
      - name: checkout actions
        uses: actions/checkout@v1
        
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: install packages
        run: "pip install --upgrade pip && pip install -r ./requirements.txt"
  
      - name: Update rss
        run: |
          cd ./src
          python ./update_rss.py

      - name: Commit report
        run:
            git config --global user.name 'wa008'
            git config --global user.email 'hzp1024@qq.com'
            git remote set-url origin https://wa008:${{ secrets.DEBIAN_REPO_TOKEN }}@github.com/wa008/zhblog.git
            git branch
            echo "hzp chechout branch"
            git checkout -b main
            git status
            git add ./README.md
            git status
            git commit -m "update rss commit"
            git status
            git push origin main

